sudo: required
dist: trusty
language: generic
notifications:
  email: false
  hipchat:
    rooms:
      secure: "QzAubhCvpG9psLesRct1IL3LLp1QGm/NS+sPOnXc839WMv+4cYpQucjW5B9QdoKVR3fuJUlsTuHOQXRxSWcv2M67YZHnZZQeVnO8ThLU5G73YG427ZF5V63MIFbZfB0cn+JUnjR9XGbbnW0i5zKisfADt5GqCT852ZJWEgNA2K4="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true
install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7 -y
  - sudo apt-get update
  - sudo apt-get install ca-certificates
  - sudo apt-get install python2.7
  - sudo apt-get install python-pip git
  - sudo apt-get install nagios-plugins-common nagios-plugins-basic # google servers kept 404ing when mid playbook, so we put it before
  - sudo pip install -U pip
  - sudo pip install paramiko PyYAML Jinja2 httplib2
  - git clone --branch v2.0.2.0-1 --depth 1 --recursive https://github.com/ansible/ansible.git ~/ansible
  - cd ~/ansible; sudo python setup.py install; cd -
before_script:
  - sed -i 's/all/127.0.0.1/' playbook.yml
  - sed -i 's/vagrant/travis/' playbook.yml
  - cp .travis.dnsmasq.yml roles/consul/tasks/dnsmasq.yml
  - cp .travis.consul.conf.j2 roles/consul/templates/consul.conf.j2
script:
  - python --version
  - PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook playbook.yml --connection=local -i 'localhost,'
