---
- hosts: all
  vars:
    deploy_user: vagrant
    deploy_setup: false
    deploy_application: redmine
    deploy_giturl: https://github.com/redmine/redmine
    deploy_gitversion: master
  roles:
    - deploy
  post_tasks:
    - name: migrate the database
      become: yes
      become_user: "{{ deploy_user }}"
      command: ~/.rbenv/shims/bundle exec rake db:migrate
      args:
        chdir: "/home/{{ deploy_user }}/{{ deploy_application }}/current"
      environment:
        RAILS_ENV: production
    - name: restart application
      supervisorctl:
        name: "{{ deploy_application }}:"
        state: restarted
