---
- hosts: all
  become: yes
  become_user: root
  vars:
    deploy_user: vagrant
    rubies:
      - 2.3.1
    global_ruby: 2.3.1
    pythons:
      - 3.5.1
    global_python: 3.5.1
    consul_aware: true
    consul_is_ui: true
    consul_is_server: true
    consul_bootstrap_expect: 1
    running_on_ec2: false
    solr_create_collections: true
    solr_collections:
      - test1
      - test2
    skip_dhparams: true
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    # - { role: naked, tags: ['naked'] } # used by exposed hosts such as Digital Ocean
    # - { role: fast_apt } # for local machines
    - { role: base, tags: ['base'] }
    - { role: java, tags: ['java'] } # required by solr
    - { role: solr, tags: ['solr'] }
    - { role: supervisor, tags: ['supervisor'] } # required by beanstalkd, consul, prometheus, redis and smokeping
    - { role: nginx, tags: ['nginx'] } # required by consul and smokeping
    - { role: consul, tags: ['consul'] } # required by beanstalkd, postgresql and redis
    - { role: prometheus, tags: ['prometheus'] }
    - { role: beanstalkd, tags: ['beanstalkd'] }
    - { role: ruby, tags: ['ruby'] }
    # - { role: python, tags: ['python'] } # conflicts with miniconda
    - { role: miniconda, tags: ['miniconda'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: memcached, tags: ['memcached'] }
    - { role: redis, tags: ['redis'] }
    - { role: rabbitmq, tags: ['rabbitmq'] }
    - { role: smokeping, tags: ['smokeping'] }
